@include('vendor-dashboard.section.header')
@yield('styles')
@include('vendor-dashboard.section.navigation')
@include('vendor-dashboard.section.notification')
@yield('main-content')
@include('vendor-dashboard.section.footer')